name: Implementation Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  foundation:

    defaults:
      run:
        shell: bash -l {0}
    name: linux-64
    runs-on: ubuntu-latest
    steps:
      # checkout the code in this repository
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.8"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install everything
        run: |
          uv sync --locked

      # checkout the main branch of ActivitySim itself
      - uses: actions/checkout@v4
        with:
          repository: 'ActivitySim/activitysim'
          ref: main
          path: 'cloned/activitysim'
          fetch-depth: 0  # get all tags, lets setuptools_scm do its thing

      # install ActivitySim, overriding the one in the workspace,
      # as the pre-installed one is the latest release but not the most up-to-date
      - name: Install ActivitySim
        run: |
          uv pip install --no-deps ./cloned/activitysim

      - name: Test this implementation
        run: |
          cd ./test
          python -m pytest test_sandag_abm3.py::test_sandag_abm3_progressive
          
